### ISSUE TITLE
评测器问题

### ISSUE THREAD

**Issue by zhizhen-chen** [hewenyang/syzoj-bzoj#2]
构建容器过程中出现npm WARN judge-daemon@0.0.1 No repository field.导致安装完成后无法进行评测。

**Comment by vincent-163** [comment]
这句话应该不是错误原因。`docker exec -it build_web_1 /bin/bash` 进去看下/root目录下的日志文件。

**Comment by zhizhen-chen** [comment]
daemon.log还是runner-1.log？

**Comment by vincent-163** [comment]
@jiaangk 都要

**Comment by zhizhen-chen** [comment]
runner-1.log   
![](https://s1.ax1x.com/2018/06/04/CT652d.jpg)

**Comment by zhizhen-chen** [comment]
sandbox-rootfs
![](https://s1.ax1x.com/2018/06/04/CT6IxA.md.jpg)

**Comment by vincent-163** [comment]
唔我忘记把这步写文档里了。。。
要在 `/etc/default/grub` 的 `GRUB_CMDLINE_LINUX_DEFAULT` 里加上选项 `swapaccount=1`.

**Comment by zhizhen-chen** [comment]
我以为这步的意思是把syzoj放到系统服务里，自己的锅

**Comment by zhizhen-chen** [comment]
还是存在无法评测的问题。![](https://s1.ax1x.com/2018/06/04/CTgd1J.md.jpg)

**Comment by vincent-163** [comment]
加上去然后sudo update-grub然后重启

**Comment by zhizhen-chen** [comment]
是不是需要把sandbox的拥有者改为root？

**Comment by vincent-163** [comment]
sandbox文件夹要全局可访问。另外刚才的问题解决了吗

**Comment by zhizhen-chen** [comment]
我把系统重装了一遍，估计还要一会儿

**Comment by zhizhen-chen** [comment]
还是不行

**Comment by vincent-163** [comment]
有日志吗，以及swapaccount=1加上去后做了uodate-grub吗

**Comment by zhizhen-chen** [comment]
已经update了，有一个warn![](https://s1.ax1x.com/2018/06/04/CTfcqA.md.jpg)
跟这个warn有关系吗？

**Comment by zhizhen-chen** [comment]
重启电脑还是容器？

**Comment by zhizhen-chen** [comment]
已成功评测！感谢
